"""empty message

Revision ID: 293800a26311
Revises: 27182e321d0c
Create Date: 2017-05-11 12:58:38.867556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293800a26311'
down_revision = '27182e321d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserInfo', sa.Column('username', sa.String(length=250), nullable=True))
    op.drop_column('UserInfo', 'email')
    op.drop_column('UserInfo', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserInfo', sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('UserInfo', sa.Column('email', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('UserInfo', 'username')
    # ### end Alembic commands ###
