"""empty message

Revision ID: 65392ac0e39a
Revises: 
Create Date: 2017-05-11 21:49:56.687995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65392ac0e39a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bucketlist', sa.Column('items', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bucketlist', 'items')
    # ### end Alembic commands ###
